/* eslint-disable */
// Stub file for development / testing.
// Convex CLI generates the real version via `npx convex dev`.

import { anyApi } from "convex/server";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * This is a stub — the real `api` is generated by `npx convex dev`.
 * convex-test can work with these references for testing.
 */
export const api = anyApi;
export const internal = anyApi;
